sites:
  - url: "https://www.sec.gov/"
  - url: "https://abc.xyz"
queries:
  - "disclosure statement"
  - "disclosure report"
  - "financial disclosures"

document_types:
  - "pdf"
  - "doc"
  - "pptx"